#ifndef _CONFIG_H_
#define _CONFIG_H_

#define WIDTH_SCREEN 640
#define HEIGHT_SCREEN 480

#define FPS_LIMIT 30.0f
#define FPS_DELAY 1000.0f / FPS_LIMIT

/********SPRITES*******/
//TIPO_NOMBRE(Archivo)_DESCRIPCION

#define MODULO_MINAVE_NAVE	0
#define MODULO_MENU_FONDO	1
#define MODULO_ENEMIGO_NAVE	2
#define MODULO_TEXTO_TITULO 3
#define MODULO_TEXTO_NOMBRE	4
#define MODULO_TEXTO_OPCION1	5
#define MODULO_TEXTO_OPCION2	6
#define MODULO_TEXTO_OPCION1_SELECCION	7
#define MODULO_TEXTO_OPCION2_SELECCION	8
#define MENU_NUMERO_ELEMENTOS	MODULO_TEXTO_OPCION1_SELECCION-MODULO_TEXTO_OPCION1

/********END*******/
#define BORDE_IZQUIERDO  1<<0  //ESTE 0001 //
#define BORDE_SUPERIOR   1<<1  //ESTE 0010//
#define BORDE_DERECHO    1<<2  //ESTE 0100//
#define BORDE_INFERIOR   1<<3  //ESTE 1000 // 




#endif
